# Generated by Django 5.0.6 on 2024-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_id', models.CharField(max_length=100)),
                ('vol_email', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100)),
                ('rz_id', models.TextField()),
                ('entity', models.TextField()),
                ('amount', models.TextField()),
                ('mode', models.TextField()),
            ],
        ),
    ]
