# Generated by Django 4.2.7 on 2024-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='timestamp1',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
