# Generated by Django 4.2.7 on 2024-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0002_payout_timestamp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='timestamp1',
            field=models.DateField(default=None, null=True),
        ),
    ]
