# Generated by Django 5.0.6 on 2024-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0003_alter_payout_timestamp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='event_name',
            field=models.CharField(null=True),
        ),
    ]
