# Generated by Django 4.2.7 on 2024-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0003_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
