# Generated by Django 5.0.6 on 2024-07-04 09:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phone1', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.TextField(default=None, null=True)),
                ('website', models.CharField(default=None, max_length=100, null=True)),
                ('phone2', models.CharField(default=None, max_length=100, null=True)),
                ('image_name', models.CharField(default=None, max_length=255, null=True)),
                ('card', models.BinaryField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image_name1', models.CharField(default=None, max_length=255, null=True)),
                ('logo', models.BinaryField(default=None, null=True)),
                ('key', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='otps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 4, 9, 41, 41, 516811, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='resetpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('keys', models.TextField()),
                ('usage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 4, 10, 36, 41, 517812, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('key', models.TextField()),
                ('role', models.CharField(default=None, max_length=20)),
                ('is_active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_visited', models.CharField(max_length=255, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('dob', models.CharField(default=None, max_length=150, null=True)),
                ('timestamp', models.CharField(default=None, max_length=250, null=True)),
                ('experience', models.CharField(default=None, max_length=200, null=True)),
                ('skills', models.CharField(default=None, max_length=200, null=True)),
                ('qualification', models.CharField(default=None, max_length=100, null=True)),
                ('upi', models.CharField(default=None, max_length=100, null=True)),
                ('emergency_contact', models.CharField(default=None, max_length=100, null=True)),
                ('image_name', models.CharField(default=None, max_length=255, null=True)),
                ('profile_pic', models.BinaryField(default=None, null=True)),
                ('image_name1', models.CharField(default=None, max_length=255, null=True)),
                ('card', models.BinaryField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('contact_id', models.CharField(max_length=200, null=True)),
                ('fund_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
