# Generated by Django 5.0.6 on 2024-07-05 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='users',
            name='timestamp',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 10, 15, 17, 687775, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 11, 10, 17, 687775, tzinfo=datetime.timezone.utc)),
        ),
    ]
