# Generated by Django 5.0.6 on 2024-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.CharField(max_length=100)),
                ('phone2', models.CharField(max_length=100)),
                ('card', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('experience', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('upi', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('card', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
    ]
