# Generated by Django 4.2.7 on 2024-07-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0002_remove_volunteer_timestamp_users_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='card',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 17, 11, 8, 907176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 18, 6, 8, 907176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='card',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.TextField(default=None, null=True),
        ),
    ]
