# Generated by Django 4.2.7 on 2024-06-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_resetpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='key',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
    ]
