# Generated by Django 4.2.7 on 2024-07-06 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_alter_company_card_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='vol_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 1, 24, 17, 923058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 2, 19, 17, 923058, tzinfo=datetime.timezone.utc)),
        ),
    ]
