# Generated by Django 4.2.7 on 2024-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_remove_company_password_remove_volunteer_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_visited', models.CharField(max_length=255)),
                ('visit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor_ip', models.CharField(max_length=50)),
                ('visitor_country', models.CharField(max_length=100)),
            ],
        ),
    ]
