# Generated by Django 4.2.7 on 2024-07-06 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_company_comp_id_volunteer_vol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 4, 41, 23, 277621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 5, 36, 23, 282757, tzinfo=datetime.timezone.utc)),
        ),
    ]
