# Generated by Django 4.2.7 on 2024-07-01 09:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0006_remove_visit_visit_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otps',
            name='usage',
        ),
        migrations.AddField(
            model_name='company',
            name='image_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='image_name1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='otps',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 9, 11, 9, 382397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='resetpass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 6, 9, 382397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image_name1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='card',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='key',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='card',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='experience',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='qualification',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='upi',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
