# Generated by Django 5.0.6 on 2024-07-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_users_role_alter_otps_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 31, 24, 478294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 26, 24, 479294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
