# Generated by Django 5.0.6 on 2024-07-01 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0010_alter_otps_expires_at_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 37, 41, 545146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 32, 41, 546144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='timestamp',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
