# Generated by Django 5.0.6 on 2024-07-01 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0011_alter_otps_expires_at_alter_resetpass_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='card',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_name1',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='key',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 43, 35, 686378, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 38, 35, 687379, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='card',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='experience',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_name1',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='qualification',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='upi',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
