# Generated by Django 5.0.6 on 2024-07-01 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0012_alter_company_address_alter_company_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 50, 28, 707780, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 45, 28, 709782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='timestamp',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
