# Generated by Django 5.0.6 on 2024-07-01 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0013_alter_company_image_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 56, 5, 334818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 51, 5, 336816, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
