# Generated by Django 5.0.6 on 2024-07-02 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0021_alter_otps_expires_at_alter_resetpass_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 21, 58, 56399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 11, 16, 58, 57398, tzinfo=datetime.timezone.utc)),
        ),
    ]
