# Generated by Django 5.0.6 on 2024-07-03 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0026_alter_otps_expires_at_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contact_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='fund_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 10, 32, 20, 188488, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 11, 27, 20, 190486, tzinfo=datetime.timezone.utc)),
        ),
    ]
