# Generated by Django 4.2.7 on 2024-07-14 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0036_alter_otps_expires_at_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 15, 55, 44, 608158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 16, 50, 44, 608158, tzinfo=datetime.timezone.utc)),
        ),
    ]
