# Generated by Django 4.2.7 on 2024-07-14 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0037_users_block_alter_otps_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 17, 53, 8, 328178, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 18, 48, 8, 328178, tzinfo=datetime.timezone.utc)),
        ),
    ]
