# Generated by Django 5.0.6 on 2024-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.CharField(max_length=200, null=True)),
                ('event_id_1', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('paid_status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='security_deposite',
        ),
        migrations.AddField(
            model_name='event',
            name='actual_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='company_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_loc_link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_mrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rep',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rep_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='reg_vol',
        ),
    ]
