# Generated by Django 5.0.6 on 2024-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regvol',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
