# Generated by Django 5.0.6 on 2024-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_event_event_company_event_event_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_loc_link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_mrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_representative',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
