# Generated by Django 5.0.6 on 2024-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_regvol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.CharField(max_length=200, null=True)),
                ('event_id_1', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('paid_status', models.BooleanField()),
            ],
        ),
    ]
