# Generated by Django 5.0.6 on 2024-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_event_event_loc_link_event_event_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='security_deposite',
        ),
        migrations.AddField(
            model_name='event',
            name='actual_amount',
            field=models.IntegerField(null=True),
        ),
    ]
