# Generated by Django 5.0.6 on 2024-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_event_security_deposite_event_actual_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_representative',
            new_name='event_rep',
        ),
        migrations.AddField(
            model_name='event',
            name='event_rep_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
