# Generated by Django 5.0.6 on 2024-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_event_representative_event_event_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
