# Generated by Django 5.0.6 on 2024-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
