# Generated by Django 5.0.6 on 2024-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_event_event_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_vol',
            old_name='company_name',
            new_name='company_email',
        ),
        migrations.AddField(
            model_name='event',
            name='company_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
