# Generated by Django 4.2.7 on 2024-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_regvol_vol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regvol',
            name='attendence',
            field=models.TextField(null=True),
        ),
    ]
