# Generated by Django 4.2.7 on 2024-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_company_name_reg_vol_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_vol',
            name='event_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reg_vol',
            name='event',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
