# Generated by Django 5.0.6 on 2024-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_payment_delete_company_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_payment',
            name='signature',
        ),
        migrations.AddField(
            model_name='company_payment',
            name='event_id',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='company_payment',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
