# Generated by Django 4.2.7 on 2024-07-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_reg_vol_event_id_alter_reg_vol_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_vol',
            old_name='event',
            new_name='event_name',
        ),
    ]
