# Generated by Django 5.0.6 on 2024-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_payment_order_id_company_payment_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_payment',
            name='signature',
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
