# Generated by Django 4.2.7 on 2024-07-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_payment',
            name='order_id',
        ),
    ]
