# Generated by Django 5.0.6 on 2024-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_payment_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_payment',
            name='amount',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='company_payment',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company_payment',
            name='event_name',
            field=models.CharField(null=True),
        ),
    ]
