# Generated by Django 4.2.7 on 2024-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_company_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_payment',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='company_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='payment_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
