# Generated by Django 4.2.7 on 2024-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_company_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_payment',
            name='order_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
