# Generated by Django 4.2.7 on 2024-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_company_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='company_payment',
            name='signature',
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='amount',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='company_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_name',
            field=models.CharField(null=True),
        ),
    ]
