# Generated by Django 4.2.7 on 2024-07-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_remove_company_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_payment',
            name='order_id',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='company_payment',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='company_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_payment',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
